[phases.setup]
nixPkgs = ["nodejs-18_x", "python39"]

[phases.install]
cmds = [
  "cd tractor-game-simulator/server && npm install --production",
  "git clone https://github.com/Roushelfy/WhoDesigned.git || echo 'Bot repo already exists'",
  "python3 -m venv who_venv",
  "source who_venv/bin/activate && pip install -r WhoDesigned/requirements.txt"
]

[phases.build]
cmds = [
  "cd tractor-game-simulator/client && npm install && npm run build"
]

[start]
cmd = "source who_venv/bin/activate && cd tractor-game-simulator/server && node src/index.js"
