export const IMPLEMENTED_RULES = Object.freeze([
  { id: 'reverse_rank_order', name: '倒反天罡' },
  { id: 'normal_game', name: '世事无常' },
  { id: 'abundant_harvest', name: '五谷丰登' },
  { id: 'extreme_challenge', name: '极限挑战' },
  { id: 'half_realm', name: '江山半壁' },
  { id: 'shared_prosperity', name: '与民同乐' },
  { id: 'perfect_strategy', name: '算无遗策' },
  { id: 'know_yourself_and_enemy', name: '知己知彼' },
  { id: 'news_minister_i', name: '新闻部长I' },
  { id: 'news_minister_ii', name: '新闻部长II' },
  { id: 'tip_of_iceberg', name: '冰山一角' },
  { id: 'mutual_visibility', name: '互通有无' },
  { id: 'double_happiness', name: '双喜临门' },
  { id: 'open_and_honest', name: '为人坦荡' },
  { id: 'ten_sided_ambush', name: '十面埋伏' },
  { id: 'irresistible_force', name: '势如破竹' },
  { id: 'single_step_debug', name: '单步调试' },
  { id: 'reform_and_opening_up', name: '改革开放' },
  { id: 'substitute_sacrifice', name: '李代桃僵' },
  { id: 'six_six_great_success', name: '六六大顺' },
  { id: 'tai_chi_four_symbols', name: '太极四象' },
  { id: 'one_horse_leads', name: '一马当先' },
  { id: 'heavy_fog', name: '迷雾重重' },
  { id: 'concealed_passage', name: '暗度陈仓' },
  { id: 'fatal_beauty', name: '红颜祸水' },
  { id: 'stealing_beams', name: '偷梁换柱' },
  { id: 'cosmic_shift', name: '斗转星移' },
  { id: 'last_stand', name: '绝处逢生' },
  { id: 'late_mover_advantage', name: '后发制人' },
  { id: 'go_with_the_flow', name: '随波逐流' },
  { id: 'frequent_fluctuation', name: '频繁波动' },
  { id: 'minor_disturbance', name: '微小扰动' },
  { id: 'lingering_discard', name: '弃掷逦迤' },
  { id: 'time_reversal', name: '时间倒流' },
  { id: 'route_swing', name: '路线摇摆' },
  { id: 'belt_and_road', name: '一带一路' },
  { id: 'day_night_rotation', name: '昼夜轮转' },
  { id: 'respect_elders_and_children', name: '尊老爱幼' },
  { id: 'rites_collapse', name: '礼崩乐坏' },
  { id: 'recommend_talent', name: '举贤任能' },
  { id: 'accident_insurance', name: '意外保险' },
  { id: 'three_powers', name: '三权分立' },
  { id: 'gentleman_promise', name: '君子一言' },
  { id: 'repeated_exhaustion', name: '再衰三竭' },
  { id: 'focus_figure', name: '焦点人物' },
  { id: 'cooldown_time', name: '冷却时间' },
  { id: 'time_cooling', name: '时间冷却' },
  { id: 'planned_economy', name: '计划经济' },
  { id: 'equivalent_reciprocity', name: '等价互惠' },
  { id: 'enduring', name: '经久不衰' },
  { id: 'average_pooling', name: '平均池化' },
  { id: 'dream_killing', name: '梦中杀人' },
  { id: 'joint_harmony', name: '珠联璧合' },
  { id: 'divine_weapon', name: '神兵天降' },
  { id: 'magic_trick', name: '魔术戏法' },
  { id: 'abrupt_stop', name: '戛然而止' },
  { id: 'cluster_analysis', name: '聚类分析' },
  { id: 'forbidden_magic', name: '禁术秘法' },
  { id: 'meticulous_accounting', name: '锱铢必较' },
  { id: 'lost_in_fog', name: '如堕云雾' },
  { id: 'birds_gone_bow_hidden', name: '鸟尽弓藏' },
  { id: 'odd_even_scoring', name: '无独有偶' },
  { id: 'second_battlefield', name: '第二战场' },
  { id: 'one_country_two_systems', name: '一国两制' },
  { id: 'wooden_ox_flowing_horse', name: '木牛流马' },
  { id: 'strength_compensation', name: '取长补短' },
  { id: 'unarmed', name: '手无寸铁' },
  { id: 'mutual_support', name: '同舟共济' },
  { id: 'candle_to_dawn', name: '烛尽天明' },
  { id: 'cultural_revolution', name: '文化革命' },
  { id: 'three_tigers', name: '三人成虎' },
  { id: 'invite_into_urn', name: '请君入瓮' },
  { id: 'old_horse_still_has_strength', name: '老骥伏枥' },
  { id: 'trump_wins', name: 'Trump wins' },
  { id: 'openly_revealed', name: '昭然若揭' },
  { id: 'straw_boat_borrowing_arrows', name: '草船借箭' },
  { id: 'bush_gate', name: '布什戈门' },
  { id: 'teammate_cheer', name: '队友加油' },
  { id: 'illusion_and_reality', name: '虚虚实实' },
  { id: 'strive_upstream', name: '力争上游' },
  { id: 'afterglow', name: '回光返照' },
  { id: 'outward_harmony_inner_division', name: '貌合神离' },
  { id: 'ambiguous', name: '模棱两可' },
  { id: 'two_ghosts_knock_door', name: '二鬼拍门' },
  { id: 'people_commune', name: '人民公社' },
  { id: 'remove_firewood_from_under_cauldron', name: '釜底抽薪' },
  { id: 'mainstay', name: '中流砥柱' },
  { id: 'happy_twins', name: '欢乐成双' },
  { id: 'encircle_three_missing_one', name: '围三阙一' },
  { id: 'three_six_nine_grades', name: '三六九等' },
  { id: 'iron_evidence', name: '铁证如山' },
  { id: 'waiting_rabbit', name: '守株待兔' },
  { id: 'hidden_dragon_in_abyss', name: '潜龙在渊' },
  { id: 'administrative_review', name: '行政审查' },
  { id: 'political_review', name: '政治审查' },
  { id: 'no_one_survives', name: '无人生还' },
  { id: 'lure_tiger_from_mountain', name: '调虎离山' },
  { id: 'defense_as_offense', name: '以守为攻' },
  { id: 'antinomy', name: '二律背反' },
  { id: 'change_rice_to_mulberry', name: '改稻为桑' },
  { id: 'destroy_dyke_flood_fields', name: '毁堤淹田' }
]);

export const RULE_SELECT_OPTIONS = IMPLEMENTED_RULES.map(rule => ({
  value: rule.id,
  label: rule.name
}));

export function ruleIncludesId(rule, ruleId) {
  if (!rule || !ruleId) return false;
  if (rule.id === ruleId) return true;
  return Array.isArray(rule.rules)
    && rule.rules.some(childRule => ruleIncludesId(childRule, ruleId));
}
